【compat】
CSV = "0.10.11"
Statistics = "1.9.0"
MPI = "0.20.15"
Distributions = "0.25.100"
TimerOutputs = "0.5.23"
JuMP = "1.15.0"
CPLEX = "1.0.0"
MLDataUtils = "0.5.4"
Luxor = "3.8.0"
StatsBase = "0.33.21"
JuliaFormatter = "1.0.36"
IJulia = "1.24.2"
DecisionTree = "0.10.12"
Plots = "1.39.0"
CategoricalArrays = "0.10.8"
Distances = "0.10.9"
RDatasets = "0.7.7"
Clustering = "0.15.4"
StaticArrays = "1.6.3"
DataFrames = "1.6.1"
